### ISSUE TITLE
[TES3MP-deploy] Add Manjaro support

### ISSUE THREAD

**Issue by Pollito001** [GrimKriegor/Misc#3]
Add manjaro support, thanks :)

**Comment by GrimKriegor** [comment]
Hello there, @Pollito001 great suggestion, if you are running Manjaro, please check what's the output of
`lsb_release -si `, thanks.

**Comment by Pollito001** [comment]
ManjaroLinux

**Comment by GrimKriegor** [comment]
Thank you, should be working now, please test it out and report back. :)

**Comment by Pollito001** [comment]
Now detect manjaro distro, but the main manjaro distro xfce4 already have pre installed gcc-libs-multilib and conflict with gcc-libs, and need libtinfo to compile tes3mp-server. Thanks

**Comment by GrimKriegor** [comment]
Thanks for letting me know, I've been skipping that conflict for a while, but didn't consider it could be troublesome for people missing the other packages.

This should help with the conflict and solve the whole libtinfo issue. https://github.com/GrimKriegor/Misc/commit/57cc55aef82127fb9c144f71f462336c635cc21c

Feel free to test. Good luck!
