### ISSUE TITLE
[TES3MP-deploy] Building older versions

### ISSUE THREAD

**Issue by Pollito001** [GrimKriegor/Misc#4]
Is posible to use this script to compile a (2016-08-24 - release 003:)  compatible client on Linux? because Linux users cant join /reg /login in the server runing from windows, even compile my on server i cant join

**Comment by GrimKriegor** [comment]
Yes indeed it is, but it will require you to checkout an older commit.

After using "install.sh" to install the dependencies, go into the "code" folder take a look at the output of

`git log`

Fnd an old commit that is from around that time, like this one

`commit d31046204f58fcb3e65b96d6dfbc7574b6fa276f
Author: David Cernat <davidcernat@gmail.com>
Date:   Tue Aug 23 23:50:20 2016 +0300

    Use tes3mp icon for executable
`

Then do

`git checkout d31046204f58fcb3e65b96d6dfbc7574b6fa276f`

And run "update.sh" to build TES3MP normally.

If you ever want to go back to the latest changes, I believe this would suffice

`git checkout master`

I've been pretty away from what awesome sorcery the guys are doing at TES3MP, and I have no idea which was the last commit included in the 003 Windows version, @davidcernat can surely let us know.

Hope this helps.

**Comment by Pollito001** [comment]
When you say update.sh you mean upgrade.sh? because i use it but nothing happens only show a message: You are not currently on a branch.

**Comment by GrimKriegor** [comment]
Oh, my bad, yes indeed I did mean "upgrade.sh".
I've just reproduced your issue, you can safely ignore it and enter "YES" to continue building. It loosely means it can't pull the latest changes, because you are not in the latest point of your local code history yourself.

Good luck!
